title: "Bakalárska práca"
author: "Nina Leoni Matušková"
description: "Denník bakalárskej práce"
permalink: /:title/
lang: "sk"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true             # show article excerpts instead of archive list on the home page
show_frame: true                # display a grey frame on large screens
show_sidebar: false             # show a sidebar instead of the usual header
show_minimal: false             # remove all clutter

#show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:
  - {file: "informacie.md", title: "Informácie", sidebaricon: info-circle}
  - {file: "prehlad.md",    title: "Prehľad",     sidebaricon: stream}
  - {file: "dennik.md",     title: "Denník",      sidebaricon: book}
  - {file: "galeria.md",    title: "Galéria",     sidebaricon: images}
  - {file: "zdroje.md",     title: "Zdroje",      sidebaricon: link}

external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: Github, icon: github, url: "https://github.com/nina-mat2004"}

plugins:
 - jekyll-feed
